[package]
name = "chrome_bug"
version = "0.1.0"
authors = ["Richard Dodd <richard.o.dodd@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
unicode-normalization = "0.1.8"
wasm-bindgen = "0.2.42"

[dev-dependencies]
wasm-bindgen-test = "0.2.42"
